"use client";
import { useState,useEffect } from 'react';
import Script from 'next/script';
import { store } from "./redux/store";
import { Provider } from "react-redux";
import { PersistGate } from 'redux-persist/integration/react';
import { persistStore } from 'redux-persist';
import Sidebar from './components/navbar/Sidebar';
import Navbar from './components/navbar/Navbar';
import Breadcrumb from './components/breadcrumb/Breadcrumb';
import './assets/css/sb-admin-2.min.css';
import './assets/css/fontawesome.css';
import './assets/vendor/datatables/dataTables.bootstrap4.min.css';
import cookieCutter from 'cookie-cutter';
import { useRouter } from 'next/navigation';
import  cookiesNames from './utils/constant/Constant';

import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] })
let persistor = persistStore(store)

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({ children }) {
  const router = useRouter()

  const [isLogin, setIsLogin] = useState(true)

  useEffect(() => {
    if(!cookieCutter.get(cookiesNames.LOG_IN)){
      setIsLogin(false)
      router.replace("/login")

    }
}, [isLogin,router]);


  return (
    <html lang="en">
      <head >
      <link rel="shortcut icon" href="#"></link>
      </head>

      <body id="page-top" 
      suppressHydrationWarning={true}
      >
        <Provider store={store}>
        <PersistGate persistor={persistor}>

          <div id="wrapper" >
            <Sidebar />

            <div id="content-wrapper" className="d-flex flex-column">
              <Navbar />
              <Breadcrumb />
              {children}
              {/* <footer className="sticky-footer bg-white">
                <div className="container my-auto">
                  <div className="copyright text-center my-auto">
                    <span>Copyright &copy; Your Website 2021</span>
                  </div>
                </div>
              </footer> */}
            </div>
          </div>
          </PersistGate>
        </Provider>
        <Script src="vendor/jquery/jquery.min.js"></Script>
        <Script src="vendor/bootstrap/js/bootstrap.bundle.min.js"></Script>

        <Script src="vendor/jquery-easing/jquery.easing.min.js"></Script>

        <Script src="js/sb-admin-2.min.js"></Script>
        {/* <Script src="js/wow.js" /> */}

        {/* <Script src="vendor/chart.js/Chart.min.js"></Script>

    <Script src="js/demo/chart-area-demo.js"></Script>
    <Script src="js/demo/chart-pie-demo.js"></Script> */}

        {/* <!-- Page level plugins --> */}
        <Script src="vendor/datatables/jquery.dataTables.min.js"></Script>
        <Script src="vendor/datatables/dataTables.bootstrap4.min.js"></Script>

        {/* <!-- Page level custom scripts --> */}
        <Script src="js/demo/datatables-demo.js"></Script>


      </body>
    </html>
  )
}
